/* eslint-disable no-undef */
describe('Found Bugs', () => {
  it('Issue #378 - Bug showing CERB twice when going back and forth', () => {
    cy.visit('/')
    cy.get('[data-cy=start]').click()
    cy.answerQuestion('#lost_joblost-some-income')
    cy.answerQuestion('#some_incomeemployed-lost-a-job')
    cy.answerQuestion('#reduced_income1000_or_less')
    cy.answerQuestion('#mortgage_paymentsno')
    cy.answerQuestion('#ccbno')
    cy.answerQuestion('#student_debtno')
    cy.answerQuestion('#plans_for_schoolno')
    cy.go('back')
    cy.go('back')
    cy.go('back')
    cy.go('back')
    cy.go('back')
    cy.go('back')
    cy.go('back')
    cy.answerQuestion('#lost_joblost-all-income')
    cy.answerQuestion('#no_incomelost-job-employer-closed')
    cy.answerQuestion('#mortgage_paymentsno')
    cy.answerQuestion('#ccbno')
    cy.answerQuestion('#student_debtno')
    cy.answerQuestion('#plans_for_schoolno')
    cy.get('[data-cy=benefit-list]').children().should('have.length', '1')
  })
})
