# Default values for dts-sab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dynatrace:
  enabled: false
  environmentId: changeme
  paasToken: changeme
  options: flavor=all&include=default

networkPolicy:
  enabled: false 
  ingressCidrBlock: 10.100.1.0/24
  egressPodMatchLabels:
    app: database

livenessProbe:
  enabled: false
  delay: 30
  path: /

readinessProbe:
  enabled: false
  delay: 30
  path: / 

replicaCount: 1

port:
  enabled: false
  name: port-name
  port: 3000
  protocol: TCP

image:
  repository: mtscontainers.azurecr.io/dts-osticket
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
