{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
  {{ if .Values.networkPolicy.ingressCidrBlock }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.ingressCidrBlock }}
        {{ if .Values.networkPolicy.ingressCidrBlockException }} 
        except:
        - {{ .Values.networkPolicy.ingressCidrBlockException }}
        {{ end }}
  {{ end }}
  {{ if .Values.networkPolicy.ingressPodMatchLabels }}
    - podSelector:
        matchLabels:
        {{- range $key, $value := .Values.networkPolicy.ingressPodMatchLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }} 
  {{ end }}
    ports:
    - protocol: TCP
      port: 3000
    egress:
    - to:
      - podSelector:
          matchLabels:
          {{- range $key, $value := .Values.networkPolicy.egressPodMatchLabels }}
          {{ $key }}: {{ $value | quote }}
          {{- end }} 
      ports:
      - protocol: TCP
        port: http
{{ end }}