name: shellcheck
on:
  pull_request:
    paths:
      - "bin/*.sh"
jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        run: shellcheck ./bin/*.sh
